apiVersion: apps/v1
kind: Deployment
metadata:
  name: ims-website
  labels:
    app: ims-website
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ims-website
  template:
    metadata:
      labels:
        app: ims-website
    spec:
      containers:
      - name: ims-website
        image: josephchuchu/ims-website:latest
        ports:
        - containerPort: 3000
        env:
        - name: NODE_ENV
          value: "production"
---
apiVersion: v1
kind: Service
metadata:
  name: ims-website-service
spec:
  type: ClusterIP
  selector:
    app: ims-website
  ports:
  - port: 80
    targetPort: 3000